title: "Security & Privacy at UIC"
email: your-email@example.com
description: "Security & Privacy group at the University of Illinois at Chicago"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uic-research.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

liquid:
  error_mode: strict

kramdown:
  syntax_highlighter: rouge

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - "jekyll/scholar"

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - tmp
  - vendor
  - _deploy

scholar:
  style: _includes/ieee.csl
  locale: en
  sort_by: year,month
  group_order: descending
  order: descending
  source: _includes
  use_raw_bibtex_entry: true
  bibliography: security.bib

# vim: set sw=2 sts=2 ts=8 expandtab:
